### ISSUE TITLE
error in running

### ISSUE THREAD

**Issue by zyu632147** [YanCCscu/MEANGS#11]
I get this problem.
tools/MEANGS/tools/assembler: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory

can you help me to see where I can get help?

**Comment by Songmh-2020** [comment]
Hi, dear user.
It seems a problem during the installation, can you tell me how you install MEANGS, via conda? or?
A quick tip: you may follow the "Quick start" - "git clone https://github.com/YanCCscu/MEANGS.git" to retry again.

Please let me know if it can help.

**Comment by zyu632147** [comment]
Well, thanks for your reply. I install MEANGS by git again. it is done well now.
