### ISSUE TITLE
Test document detects errors

### ISSUE THREAD

**Issue by luozhisen** [YanCCscu/MEANGS#12]
Dear Song,
         I can run the code with the example data, but I have a data formatting error with my own data, but I use the code zgrep -m 1 'N' your_fastq_file.fq.gz # to check the sequence for N and zgrep -c "^@" 1.fq.gz # to check if the data is damaged. The result is no problem, so I would like to consult you.
         run: meangs.py -1 GOU101647A_1_trimmed.fq.gz -2 GOU101647A_2_trimmed.fq.gz -o example_out -t 16 -n 5000000 -i 300 --deepin
         error:
         >>>Starting reading reads: 2024-3-29-8:23:33
Input error at line 1: The sequence "" is not in the right format for paired-end reads  -- Fatal
Make sure your input is in the form (input sequences can be of variable lengths):

>test
GCTACGACTATGACATACAGT:GTAGATTGATCGCATGCACGCT
Where : separates paired reads.  Spaces, <<.>> or any characters other than A,C,G or T in your input file might have caused this error, including reads with Ns.
         
        No "Ns" in reads

**Comment by Songmh-2020** [comment]
Solved by change -n setting.
