### ISSUE TITLE
Mutiple scaffolds with many same genes

### ISSUE THREAD

**Issue by jiangzy26** [YanCCscu/MEANGS#13]
Hi, I am trying your method to construct the mt genome, it is very fast which surprised me, My fastq data quality is not very good, I found the final result has multiple scaffolds and many same genes were assembled multiple times, they didn't same either, could you share your help about how I get the mt genome, or at least the 13 protein-coding genes, how I remove those redundant results? 

Thank you.

**Comment by Songmh-2020** [comment]
Dear MEANGS User,

Thank you for using MEANGS! Based on your description, here are a few suggestions that may help resolve the issue:

1. Multiple scaffold results can occur if the sequencing depth is insufficient. If the same gene name is generated more than once, you could extract the sequences and use BLAST to verify the results. Often, these may represent fragments of the same gene (e.g., ND1) that were assembled as separate fragments.

2. If you are using the "-n" parameter during assembly, try increasing the value or removing the "-n" flag to see if that resolves the issue.

3. If you are already using the full sequencing data (without the "-n" flag) but still cannot obtain the complete mitochondrial genome, you could use the MEANGS output as a seed and try running NOVOPLASTY to improve the assembly. However, be cautious, especially if your data has low coverage, as this can affect the accuracy of the results.

4. If you're trying to retrieve all 13 protein-coding genes, removing the "--deepin" option should help you get the full set.

If you wanna more advice, please contact and attach your results or log file for us.

Best regards,
Menghuan

**Comment by wangjie07070910** [comment]
I'm actually facing the same problem, the WGS sequencing depth of my samples should be ok, around 10x. I'm using without --deepin mode. I got a file called detected_mito.fas with a lot of scaffold in it. any suggestions? Thank you :)

**Comment by Songmh-2020** [comment]
> I'm actually facing the same problem, the WGS sequencing depth of my samples should be ok, around 10x. I'm using without --deepin mode. I got a file called detected_mito.fas with a lot of scaffold in it. any suggestions? Thank you :)

Could you provide your script? It is normal because the PCGs may arrange linear in the mitogenome.

**Comment by wangjie07070910** [comment]
python $MEANGS_SCRIPT -1 $CLEAN_DATA_1 -2 $CLEAN_DATA_2 -o $SAMPLE_ID -t 40 -i 200  --species_class Chordata
I can also send you my output through email :)

**Comment by Songmh-2020** [comment]
> python $MEANGS_SCRIPT -1 $CLEAN_DATA_1 -2 $CLEAN_DATA_2 -o $SAMPLE_ID -t 40 -i 200 --species_class Chordata I can also send you my output through email :)

Did you try to use the --deepin mode? What will be generated?

**Comment by wangjie07070910** [comment]
I did not try --deepin mode, will do it for comparison now.

**Comment by wangjie07070910** [comment]
This is my previous results

**Comment by Songmh-2020** [comment]
> I did not try --deepin mode, will do it for comparison now.

Hi, I checked your result and I think they are good. Without --deepin parameter, MEANGS will give you the assemblies based on the poteintal PCGs fragment reads. It is normal to have results like these since in the mitogenome the PCGs are not connected linear.

So far I can't get your point about what you wanna do with MEANGS, please let me know it.
