### ISSUE TITLE
-i 命令后的数值，根据什么判断应该填多少

### ISSUE THREAD

**Issue by laizhengjiao** [YanCCscu/MEANGS#14]
-i 命令后的数值，根据什么判断应该填多少

**Comment by Songmh-2020** [comment]
-i INSERT, library insert length
See description: (https://knowledge.illumina.com/library-preparation/general/library-preparation-general-reference_material-list/000003874)
可以联系测序公司获得相关信息。

**Comment by laizhengjiao** [comment]
您好，像这种有些基因没组装出来，结果文件也不是单独的一个fasta，这种情况怎么办？

从 网易邮箱大师 发来的云附件
|
| |
| |
|
| |
| 扫描20240912190654.JPG |
| |
| 14.4M · 存在有效期 |
| |
| 下载 |
| |
| |
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月12日 19:05 |
| 收件人 | YanCCscu/MEANGS ***@***.***> |
| 抄送人 | laizhengjiao ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [YanCCscu/MEANGS] -i 命令后的数值，根据什么判断应该填多少 (Issue #14) |

Closed #14 as completed.

**Comment by Songmh-2020** [comment]
1. 确保你的数据测序深度足够 如果 ddrad 数据 以及测序深度低于 5X 组装可能存在不完全
2. 增加 -n 参数的设置。
3. 参考#13 解决办法。
4. 使用 --deepin 参数

**Comment by laizhengjiao** [comment]
这是我从网上down的原始数据，想学习使用meangs，是不是这个insert片段设置不对，也会影响结果？

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月12日 19:05 |
| 收件人 | YanCCscu/MEANGS ***@***.***> |
| 抄送人 | laizhengjiao ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [YanCCscu/MEANGS] -i 命令后的数值，根据什么判断应该填多少 (Issue #14) |

Closed #14 as completed.

**Comment by Songmh-2020** [comment]
insert 通常不会影响结果。

**Comment by laizhengjiao** [comment]
谢谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月12日 19:17 |
| 收件人 | YanCCscu/MEANGS ***@***.***> |
| 抄送人 | laizhengjiao ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [YanCCscu/MEANGS] -i 命令后的数值，根据什么判断应该填多少 (Issue #14) |

确保你的数据测序深度足够 如果 ddrad 数据 以及测序深度低于 5X 组装可能存在不完全
增加 -n 参数的设置。
参考#13 解决办法。
使用 --deepin 参数

**Comment by laizhengjiao** [comment]
好的，谢谢您的解答

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月12日 19:19 |
| 收件人 | YanCCscu/MEANGS ***@***.***> |
| 抄送人 | laizhengjiao ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [YanCCscu/MEANGS] -i 命令后的数值，根据什么判断应该填多少 (Issue #14) |

insert 通常不会影响结果。
