### ISSUE TITLE
availability in Conda?

### ISSUE THREAD

**Issue by AntonioBaeza** [YanCCscu/MEANGS#2]
Great tool. Any chance you can make it available via Conda? Thanks!

**Comment by Songmh-2020** [comment]
Hi, thank you! You provide a wonderful suggestion, and we will upload our tool and make it available via Conda in a few days. We will let you know when we finished it. : )

**Comment by cebos** [comment]
Any update on this?

**Comment by Songmh-2020** [comment]
Hi, the compiled software is provided now. Therefore, you can directly download it and use it. 
Please just to have a try if you need. Thank you.

**Comment by AntonioBaeza** [comment]
Fantastic, thank you. I will try it soon? Reading the instructions, I understand that there is no need for a 'seed'? Thank you.

**Comment by Songmh-2020** [comment]
@AntonioBaeza Thank you for using. Please contact us without hesitation if you need any suggestions or help.

**Comment by Songmh-2020** [comment]
@AntonioBaeza @cebos Hi, guys. Sorry for the late update. MEANGS is now available in Anaconda. You can use "conda install -c yccscucib meangs" to install it via conda and hope MEANGS is useful for you.
If you have any questions, please contact us without hesitation. 
This comment will be closed. Thank you!

**Comment by cebos** [comment]
While I can clearly see MEANGS listed on the anaconda website (https://anaconda.org/yccscucib/meangs), I strangely am unable to install using conda, I've copied my terminal log below:

`conda install -c yccscucib meangs
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - meangs

Current channels:

  - https://conda.anaconda.org/yccscucib/osx-64
  - https://conda.anaconda.org/yccscucib/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(base) CollinsMBP1679:~ collinbos$ conda install -c yccscucib meangs
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - meangs

Current channels:

  - https://conda.anaconda.org/yccscucib/osx-64
  - https://conda.anaconda.org/yccscucib/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.`
