### ISSUE TITLE
Ask for test datasets

### ISSUE THREAD

**Issue by comery** [YanCCscu/MEANGS#3]
Dear Authors,

Could you share the datasets that you applied to test the performance of MEANGS and the other three software? I saw your paper you uploaded to Researchgate and the information of data availability in that, but it's not open assess, so I can find your Supplementary Data.

**Comment by Songmh-2020** [comment]
Hi,

It is easy to use this website https://academic.oup.com/bib/advance-article-abstract/doi/10.1093/bib/bbab538/6481918 to find our paper and you can try to download the "Supplementary Data" in "Availability". In the download word file, you can find all the SRA id and mitochondrial DNA id we used.
If it doesn't work, please tell me here.

**Comment by Songmh-2020** [comment]
> Dear Authors,
> 
> Could you share the datasets that you applied to test the performance of MEANGS and the other three software? I saw your paper you uploaded to Researchgate and the information of data availability in that, but it's not open assess, so I can find your Supplementary Data.

Hi,

It is easy to use this website https://academic.oup.com/bib/advance-article-abstract/doi/10.1093/bib/bbab538/6481918 to find our paper and you can try to download the "Supplementary Data" in "Availability". In the download word file, you can find all the SRA id and mitochondrial DNA id we used.
If it doesn't work, please tell me here.

**Comment by comery** [comment]
Thank you! it works well.
