### ISSUE TITLE
Fungi mit_genome

### ISSUE THREAD

**Issue by cfz1998** [YanCCscu/MEANGS#5]
Hi! Could i using MEANGS for fungi_mit assemble and anno? @Songmh-2020 

Thank you for your reply!

--zcf

**Comment by Songmh-2020** [comment]
@cfz1998 Hi, thank you for your question. MEANGS is designed only for the animal's mitogenome assembly and annotation. You can try to use other tools to deal with your problem.

**Comment by cfz1998** [comment]
> 
Hi @Songmh-2020 
How to build fungi *_CDS.hmm like animals?

**Comment by Songmh-2020** [comment]
Yes, you can have a try on MITGARD. 

Welcome to use MEANGS when you need it. @cfz1998
