### ISSUE TITLE
Cestode mitogenome

### ISSUE THREAD

**Issue by kenziegrover** [YanCCscu/MEANGS#6]
Hello, 

I would like to assemble mitogenomes for cestodes, however there is no CDS.hmm option for tapeworms. Is there a way to find one on HMMER or other sites? Is it possible to automate the construction of one using cestode mitogenomes? Is there another way to assemble a hmm file for cestodes? 

Thank you!

**Comment by Songmh-2020** [comment]
Hi, thank you for your question. You may try to use the category close related to your species and check the results. If you have partial result, you may use other tools to assemble the full mitogenome.
You can contact me if you have any question.
