### ISSUE TITLE
Parameterization Help

### ISSUE THREAD

**Issue by cebos** [YanCCscu/MEANGS#7]
Dear YanCCscu,

I have managed to install and run MEANGS, however, the assembly it produced is not very probable (MEANGS produced a 11993bp contig, in comparison to the 15601bp contig produced by NOVOPlasty). Are there any parameter changes you would suggest to produce a more plausible mito genome assembly?

This is the command I used:
`./meangs.py -1 /work/bos/mitogenomes/test_project/test_data/fastp_test2/PE_outs/Stumpffia_miery_ZCMV-5868_L001_R1.out.fq.gz -2 /work/bos/mitogenomes/test_project/test_data/fastp_test2/PE_outs/Stumpffia_miery_ZCMV-5868_L001_R2.out.fq.gz -o Stumpffia_miery_ZCMV-5868 -t 16 -i 300 --deepin --clip --silence
`

If it helps, I can also attach the log of the MEANGS run I saved from the terminal.

**Comment by Songmh-2020** [comment]
Dear @cebos, hi~
Sorry for the late reply. Based on your descriptions and command, it is hard to say what happened during the assembly. I would like to see your log file.
Also, two points may help:
1. you mentioned that MEANGS produced a 11993bp contig. Does it only produce one contig or several contigs? If there are several contigs (containing different motifs/CDs) you may need to put them together as a partial mitogenome. As we mentioned in our article as well as the Note section, if there were structural anomalies, the sequences would break at the points. So you can have a look on the results.
2. Have you checked the results generated by NOVOPlasty? Is it right or not?

**Comment by cebos** [comment]
Hi Songmh-2020,
I've attached a text file of the log below, the program only produced a single contig. The results I got from NOVOPlasty seem plausible, no genes were missing (although there may have been one or two tRNAs missing). In regards to your point about structural anomalies, if I understand correctly, does the program struggle with these? I'm planning to perform many de novo mitochondrial assemblies for a group of animals that shows variation in mitochondrial genome structure, is MEANGS not suited for this? 

[Stumpffia_miery_ZCMV-5868_log.txt](https://github.com/YanCCscu/MEANGS/files/11147358/Stumpffia_miery_ZCMV-5868_log.txt)

**Comment by Songmh-2020** [comment]
@cebos Hi~
I saw your log file. It seems that the program works well. What makes me amazing is that NOVOPlaty can assemble a plausible (longer) result. Can you send me the results of two tools? Also, would you please tell me that the seed file used for NOVOPlasty is what, whole mitogenome sequences or a partial coding sequences？From what (the species itself or its close related species)?

**Comment by Songmh-2020** [comment]
@cebos Hi~
I saw your log file. It seems that the program works well. What makes me amazing is that NOVOPlaty can assemble a plausible (longer) result. Can you send me the results of two tools? Also, can you please tell me that the seed file used for NOVOPlasty. Whole mitogenome sequence or a partial coding sequence? From the species itself or its closely related species?

**Comment by cebos** [comment]
Hi, a couple things just to update you on this, 
1. most of my sequence data is hybrid enrichment target capture data, which de novo methods aren't exactly designed for, but I'm giving it a try
2. I used a partial coding sequence in novoplasty from a related species

**Comment by cebos** [comment]
Sorry to jump between issue threads (as I opened another related to being unable to run the program), I thought it would be best to post this here since the command I used on March 23 (above) now produces the following error:

`2023-09-21 00:53:36 Now create outBase directory
[E::stk_trimfq] failed to open the input file/stream.
[E::stk_trimfq] failed to open the input file/stream.
fm_general.c: Error reading meta data for FM index.
fm_general.c: Error reading meta data for FM index.`


`Error occured when running command:
/work/bos/mitogenomes/FROGS/MEANGS/tools/nhmmer -o /work/bos/mitogenomes/FROGS/MEANGS/Stumpffia_miery_ZCMV-5868/Stumpffia_miery_ZCMV-5868_2_hmmout --tblout /work/bos/mitogenomes/FROGS/MEANGS/Stumpffia_miery_ZCMV-5868/Stumpffia_miery_ZCMV-5868_2_hmmout_tbl --cpu 16 /work/bos/mitogenomes/FROGS/MEANGS/tools/CDS_HMM/Chordata_CDS.hmm /work/bos/mitogenomes/FROGS/MEANGS/Stumpffia_miery_ZCMV-5868/Stumpffia_miery_ZCMV-5868_2.input.fas
Error occured when running command:
/work/bos/mitogenomes/FROGS/MEANGS/tools/nhmmer -o /work/bos/mitogenomes/FROGS/MEANGS/Stumpffia_miery_ZCMV-5868/Stumpffia_miery_ZCMV-5868_1_hmmout --tblout /work/bos/mitogenomes/FROGS/MEANGS/Stumpffia_miery_ZCMV-5868/Stumpffia_miery_ZCMV-5868_1_hmmout_tbl --cpu 16 /work/bos/mitogenomes/FROGS/MEANGS/tools/CDS_HMM/Chordata_CDS.hmm /work/bos/mitogenomes/FROGS/MEANGS/Stumpffia_miery_ZCMV-5868/Stumpffia_miery_ZCMV-5868_1.input.fas
Traceback (most recent call last):
  File "./meangs.py", line 182, in <module>
    mitoReads_withdraw(args.outBase,seqtk,args.outBase+"_1"+"_hmmout_tbl",\
  File "./meangs.py", line 94, in mitoReads_withdraw
    with open(tbl) as hmmtbl:
FileNotFoundError: [Errno 2] No such file or directory: '/work/bos/mitogenomes/FROGS/MEANGS/Stumpffia_miery_ZCMV-5868/Stumpffia_miery_ZCMV-5868_1_hmmout_tbl'`

**Comment by cebos** [comment]
I just reinstalled using the conda install with an updated version of conda and it's all working! I'll close this for now then :)
