### ISSUE TITLE
The meanings of

### ISSUE THREAD

**Issue by deyuanyang** [YanCCscu/MEANGS#8]

**Comment by deyuanyang** [comment]
Hi Song,


Would you mind giving more detail to explain the file of results?

Best wishes

Deyuan

**Comment by Songmh-2020** [comment]
Hi @deyuanyang 
Sorry for reply so late. Actually, I can't fully understand your meaning. I list several points based on my understanding.
1. The results file always contain one single or several contigs and they are the mitochondrial DNA sequences. 
2. The head (>. X..X..X..X..X) is like a bed file format. It tells the annotation of PCGs and their positions. For example: CO1 1..155 means that in the target sequence, the CO1 gene locates at position 1 to 155. (This annotation is usually correct)
Hope it works for you.

Please contact with us without hesitation if you have any question during the use.

Menghuan Song

**Comment by deyuanyang** [comment]
Hi Menghuan,


Sorry to cause you trouble in understanding.

yes, you gave me a good explanation of the results file.

Many thanks.

Best wishes
Deyuan
